theme: jekyll-theme-hacker
name: Ramblings of a Greybeard
markdown: kramdown
plugins:
  - jekyll-relative-links
  - jekyll-theme-slate
relative_links:
  enabled: true
  collections: true
github:
  is_project_page: false
  